API_ENDPOINT = "/registry"
SYNC = "/sync"
SYNC_SEARCH_ENDPOINT = API_ENDPOINT + SYNC + "/search"

INDIVIDUAL = "G2P:RegistryType:Individual"

REG_TYPE_CHOICES = [INDIVIDUAL]

GRAPHQL = "graphql"

ALLOWED_QUERY_TYPE = [GRAPHQL]
